//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akun
    {
        public Akun()
        {
            this.TransaksiHeader = new HashSet<TransaksiHeader>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Nama { get; set; }
        public System.DateTime TanggalLahir { get; set; }
        public string NomorTelepon { get; set; }
        public bool MerupakanAdmin { get; set; }
    
        public virtual ICollection<TransaksiHeader> TransaksiHeader { get; set; }
    }
}
