//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class KodePromo
    {
        public KodePromo()
        {
            this.TransaksiHeader = new HashSet<TransaksiHeader>();
        }
    
        public int ID { get; set; }
        public string Kode { get; set; }
        public double PersentaseDiskon { get; set; }
        public double MaksimumDiskon { get; set; }
        public System.DateTime BerlakuSampai { get; set; }
        public string Deskripsi { get; set; }
    
        public virtual ICollection<TransaksiHeader> TransaksiHeader { get; set; }
    }
}
