//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BromoAirlinesEntities : DbContext
    {
        public BromoAirlinesEntities()
            : base("name=BromoAirlinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Akun> Akun { get; set; }
        public DbSet<Bandara> Bandara { get; set; }
        public DbSet<JadwalPenerbangan> JadwalPenerbangan { get; set; }
        public DbSet<KodePromo> KodePromo { get; set; }
        public DbSet<Maskapai> Maskapai { get; set; }
        public DbSet<Negara> Negara { get; set; }
        public DbSet<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangan { get; set; }
        public DbSet<StatusPenerbangan> StatusPenerbangan { get; set; }
        public DbSet<TransaksiDetail> TransaksiDetail { get; set; }
        public DbSet<TransaksiHeader> TransaksiHeader { get; set; }
    }
}
