//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negara
    {
        public Negara()
        {
            this.Bandara = new HashSet<Bandara>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public string IbukotaNegara { get; set; }
    
        public virtual ICollection<Bandara> Bandara { get; set; }
    }
}
