//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantarBooks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buku
    {
        public int ID { get; set; }
        public string KodeBuku { get; set; }
        public string Judul { get; set; }
        public int KategoriID { get; set; }
        public string Pengarang { get; set; }
        public string Penerbit { get; set; }
        public int TahunTerbit { get; set; }
        public double Harga { get; set; }
        public int Stok { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
