//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantarBooks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public Kategori()
        {
            this.Buku = new HashSet<Buku>();
        }
    
        public int ID { get; set; }
        public string NamaKategori { get; set; }
        public string Deskripsi { get; set; }
    
        public virtual ICollection<Buku> Buku { get; set; }
    }
}
