//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantarBooks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NusantaraBooksEntities : DbContext
    {
        public NusantaraBooksEntities()
            : base("name=NusantaraBooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Akun> Akun { get; set; }
        public DbSet<Buku> Buku { get; set; }
        public DbSet<Kategori> Kategori { get; set; }
    }
}
